version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: savings
    restart: unless-stopped
    environment:
      POSTGRES_DB: savings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d savings"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: