spring:
  application:
    name: savings

  datasource:
    url: jdbc:postgresql://localhost:5432/savings
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 1000 # Set connection timeout to 1 second
      max-lifetime: 30000 # Set max lifetime for connections to 30 seconds
      validation-timeout: 1000 # Set validation timeout to 1 second

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Caffeine Cache Configuration
  cache:
    type: caffeine

# Resilience4j Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      createAccountCircuitBreaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
      getAccountCircuitBreaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
      accountsByCustomerNameCircuitBreaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
  timelimiter:
    instances:
      getAccountTimeLimiter:
        timeout-duration: 1s
        cancel-running-future: true
  retry:
    instances:
      getAccountRetry:
        max-attempts: 3 # Number of retry attempts
        wait-duration: 1s # Wait time between attempts

logging:
  level:
    root: INFO
    com.roshlab.savings: DEBUG

# Nickname check feature
feature:
  nicknameCheck: true

validation:
  nickname:
    file: nickname.txt

springdoc:
  swagger-ui:
    url: /openapi.yaml
    disable-swagger-default-url: true

---
spring:
  application:
    name: savings

  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/savings
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 1000 # Set connection timeout to 1 second
      max-lifetime: 30000 # Set max lifetime for connections to 30 seconds
      validation-timeout: 1000 # Set validation timeout to 1 second

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  docker:
    compose:
      file: docker-compose.dev.yml
      lifecycle-management: start_and_stop

  # Caffeine Cache Configuration
  cache:
    type: caffeine

# Resilience4j Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      createAccountCircuitBreaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
      getAccountCircuitBreaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
      accountsByCustomerNameCircuitBreaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
  timelimiter:
    instances:
      getAccountTimeLimiter:
        timeout-duration: 1s
        cancel-running-future: true
  retry:
    instances:
      getAccountRetry:
        max-attempts: 3 # Number of retry attempts
        wait-duration: 1s # Wait time between attempts

logging:
  level:
    root: INFO
    com.roshlab.savings: INFO
    org.hibernate.SQL: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: trace

# Nickname check feature
feature:
  nicknameCheck: true

validation:
  nickname:
    file: nickname.txt

springdoc:
  swagger-ui:
    url: /openapi.yaml # Points to openapi.yaml static file under resources/static/
    disable-swagger-default-url: true # Prevent loading the default, empty API docs.