# This workflow automates the build and test process for Savings Service Project
name: Savings Service CI Pipeline

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

# Set up separate jobs for Build and Test for scalability
jobs:
  # Build the application artifacts
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle (skip tests)
        run: ./gradlew build -x test

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'build-jar'
          path: 'build/libs/'

  # Run tests
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: 'build-jar'

      - name: Run Gradle tests
        run: ./gradlew test